package com.example.demo

class CriminalData(
        var _id: String? = null,
        var nameType: String? = null,
        var blank: String? = null,
        var name: String? = null,
        var blank1: String? = null,
        var pid: String? = null,
        var blank2: String? = null,
        var partyCode: String? = null,
        var blank3: String? = null,
        var defendantCaseNumber: String? = null,
        var blank4: String? = null,
        var division: String? = null,
        var blank5: String? = null,
        var sex: String? = null,
        var blank6: String? = null,
        var race: String? = null,
        var blank7: String? = null,
        var dateOfBirth: String? = null,
        var blank8: String? = null,
        var dateOfFiling: String? = null,
        var blank9: String? = null,
        var numberOfCount: String? = null,
        var blank10: String? = null,
        var levelOfCount: String? = null,
        var blank11: String? = null,
        var chargeDescription: String? = null,
        var blank12: String? = null,
        var dispositionCode: String? = null,
        var blank13: String? = null,
        var dispositionDate: String? = null
)